[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  GITHUB_OWNER = "stakewindows63"
  GITHUB_REPO = "file"
  GITHUB_BRANCH = "main"
  GITHUB_FOLDER = ""

[functions]
  node_bundler = "esbuild"
